import { z } from "zod";
import { normalizeCnpj, validateCommercialTransition } from "../shared/crmRules";
import { TRPCError } from "@trpc/server";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { bulkUpsertCompanies, createImportFailureNotification, createActivity, createCompany, createContact, createRegulatoryAct, createEvidenceFile, createImportRun, decideImportConflict, completeRecurringItem, createLead, createOpportunity, createRecurringItem, archiveEvidenceFile, updateRegulatoryAct, archiveRegulatoryAct, createUnit, updateUnit, updateContact, archiveUnit, archiveContact, finishImportRun, getCommercialFunnelSummary, getDashboardStats, getLeadTransitionEvidence, getOperationalCoverage, getCetesbLeadStatus, convertLeadToClient, updateOpportunityDetails, listCompanies, listContacts, listEvidenceFiles, listImportRuns, listPendingImportConflicts, listLeads, listNotifications, listOpportunities, listOperationalQueue, listRecentActivities, listRegulatoryActs, listUpcomingRecurring, listUnits, markNotificationRead, updateLeadCommercialStatus, updateOpportunityStage, updateOpportunityStageWithLossReason, getRaizonProfile, upsertRaizonProfile, listServiceCatalog, createServiceCatalogItem, updateServiceCatalogItem, archiveServiceCatalogItem, listProposals, createProposalFromRefs, updateProposalDetails, updateProposalStatus, createProposalVersion, issueProposal, listExecutionProjects, getExecutionProjectDetails, createExecutionProjectFromProposal, updateExecutionProjectStatus, createProjectTask, updateProjectTaskStatus, updateProjectChecklistStatus, listProjectEvidence, createProjectEvidence, getIntelligenceRadar, getCommercialMetrics, runProposalFollowUps, recordRegulatoryValidation, listIntelligenceSuggestions, createIntelligenceSuggestion, reviewIntelligenceSuggestion } from "./db";
import { lookupCnpj } from "./integrations/cnpj";
import { storagePut } from "./storage";
import { normalizeDateValue, normalizeEmailValue, normalizeMunicipalityValue, normalizePersistedDates, normalizePhoneValue } from "../shared/normalization";
import { validateDocxTemplateMetadata } from "../shared/templateRules";
import { canUploadProjectEvidence, MAX_PROJECT_EVIDENCE_BYTES } from "../shared/executionRules";
import { canProfileUpdateProposalStatus } from "../shared/proposalRules";
import { sendTitanEmail } from "./email";
import { invokeLLM } from "./_core/llm";

const cnpjSchema = z.string().transform(normalizeCnpj).refine((value) => value.length === 14, "CNPJ deve conter 14 dígitos");
const leadStageSchema = z.enum(["new", "enrichment", "actionable", "contacted", "qualified", "diagnosis", "scoping", "proposal", "negotiation", "approved", "won", "lost", "nurture", "discarded"]);
const proposalStatusSchema = z.enum(["draft", "technical_review", "commercial_review", "approved_internal", "issued", "sent", "negotiating", "accepted", "rejected", "cancelled"]);
function requireProfile(ctx: { user: { role: string; profile: string } }, allowed: Array<"admin" | "commercial" | "technical">) {
  const profile = ctx.user.role === "admin" ? "admin" : ctx.user.profile;
  if (!allowed.includes(profile as never)) throw new TRPCError({ code: "FORBIDDEN", message: "Perfil sem permissão para esta operação." });
}

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return { success: true } as const;
    }),
  }),
  raizon: router({
    profile: protectedProcedure.query(({ ctx }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return getRaizonProfile(); }),
    update: protectedProcedure.input(z.object({ legalName: z.string().min(2), tradeName: z.string().optional(), cnpj: z.string().optional(), responsibleName: z.string().optional(), professionalTitle: z.string().optional(), crea: z.string().optional(), mte: z.string().optional(), phone: z.string().optional(), email: z.string().email().optional().or(z.literal("")), address: z.string().optional(), addressNumber: z.string().optional(), addressComplement: z.string().optional(), neighborhood: z.string().optional(), postalCode: z.string().optional(), city: z.string().optional(), state: z.string().length(2).optional(), signatureText: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin"]); return upsertRaizonProfile({ ...input, cnpj: input.cnpj ? normalizeCnpj(input.cnpj) : undefined, email: input.email || undefined, state: input.state?.toUpperCase(), phone: normalizePhoneValue(input.phone) || undefined }); }),
  }),
  services: router({
    list: protectedProcedure.input(z.object({ includeInactive: z.boolean().optional() }).optional()).query(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return listServiceCatalog(input?.includeInactive ?? false); }),
    create: protectedProcedure.input(z.object({ name: z.string().min(2), category: z.string().min(2), agency: z.string().optional(), state: z.string().length(2).optional(), summary: z.string().optional(), scope: z.string().min(10), deliverables: z.string().min(5), requiredDocuments: z.string().optional(), exclusions: z.string().optional(), assumptions: z.string().optional(), defaultVisits: z.number().int().min(0).max(99).default(0), basePrice: z.string().optional(), templateKey: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return createServiceCatalogItem({ ...input, state: input.state?.toUpperCase(), basePrice: input.basePrice || undefined }); }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive(), name: z.string().min(2).optional(), category: z.string().min(2).optional(), agency: z.string().optional(), state: z.string().length(2).optional(), summary: z.string().optional(), scope: z.string().min(10).optional(), deliverables: z.string().min(5).optional(), requiredDocuments: z.string().optional(), exclusions: z.string().optional(), assumptions: z.string().optional(), defaultVisits: z.number().int().min(0).max(99).optional(), basePrice: z.string().optional(), templateKey: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); const { id, ...changes } = input; return updateServiceCatalogItem(id, { ...changes, state: changes.state?.toUpperCase(), basePrice: changes.basePrice || undefined }); }),
    archive: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return archiveServiceCatalogItem(input.id); }),
    attachTemplate: protectedProcedure.input(z.object({ id: z.number().int().positive(), filename: z.string().min(1).max(255), mimeType: z.string().min(1).max(120), base64: z.string().max(7_000_000) })).mutation(async ({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); const { normalizedFilename, mimeType } = validateDocxTemplateMetadata(input.filename, input.mimeType); const buffer = Buffer.from(input.base64, "base64"); if (buffer.byteLength > 5 * 1024 * 1024) throw new TRPCError({ code: "PAYLOAD_TOO_LARGE", message: "Templates devem ter no máximo 5 MB." }); const stored = await storagePut(`templates/services/${ctx.user.id}/${input.id}/${normalizedFilename}`, buffer, mimeType); await updateServiceCatalogItem(input.id, { templateKey: stored.key }); return { key: stored.key, url: stored.url }; }),
  }),
  proposals: router({
    list: protectedProcedure.query(({ ctx }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return listProposals(); }),
    create: protectedProcedure.input(z.object({ opportunityId: z.number().int().positive(), companyId: z.number().int().positive(), unitId: z.number().int().positive().optional(), contactId: z.number().int().positive().optional(), serviceId: z.number().int().positive(), investment: z.string().min(1), paymentTerms: z.string().max(255).optional(), validityDays: z.number().int().min(1).max(365).default(20), visitsIncluded: z.number().int().min(0).max(99).optional(), missingInformation: z.string().optional(), notes: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial"]); return createProposalFromRefs({ ...input, ownerId: ctx.user.id }); }),
    updateDetails: protectedProcedure.input(z.object({ id: z.number().int().positive(), investment: z.string().min(1).optional(), paymentTerms: z.string().max(255).optional(), validityDays: z.number().int().min(1).max(365).optional(), visitsIncluded: z.number().int().min(0).max(99).optional(), missingInformation: z.string().optional(), notes: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial"]); const { id, ...changes } = input; return updateProposalDetails(id, changes); }),
    updateStatus: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: proposalStatusSchema })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); if (!canProfileUpdateProposalStatus(ctx.user.profile, ctx.user.role, input.status)) throw new TRPCError({ code: "FORBIDDEN", message: "O perfil técnico pode apenas encaminhar a proposta para revisão técnica." }); return updateProposalStatus(input.id, input.status, ctx.user.id); }),
    createVersion: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial"]); return createProposalVersion(input.id, ctx.user.id); }),
    issue: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial"]); return issueProposal(input.id, ctx.user.id); }),
  }),
  execution: router({
    list: protectedProcedure.query(({ ctx }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return listExecutionProjects(); }),
    details: protectedProcedure.input(z.object({ projectId: z.number().int().positive() })).query(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return getExecutionProjectDetails(input.projectId); }),
    createFromProposal: protectedProcedure.input(z.object({ proposalId: z.number().int().positive(), title: z.string().max(255).optional(), startAt: z.date().optional(), dueAt: z.date().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return createExecutionProjectFromProposal({ ...input, ownerId: ctx.user.id }); }),
    updateStatus: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["planning", "in_progress", "blocked", "delivered", "accepted", "closed", "cancelled"]), acceptanceNotes: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return updateExecutionProjectStatus(input.id, input.status, input.acceptanceNotes); }),
    createTask: protectedProcedure.input(z.object({ projectId: z.number().int().positive(), title: z.string().min(3).max(255), category: z.string().max(100).optional(), ownerId: z.number().int().positive().optional(), dueAt: z.date().optional(), notes: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return createProjectTask({ ...input, ownerId: input.ownerId ?? ctx.user.id }); }),
    updateTaskStatus: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["open", "in_progress", "blocked", "done", "cancelled"]) })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return updateProjectTaskStatus(input.id, input.status); }),
    updateChecklistStatus: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["pending", "received", "approved", "rejected", "waived"]), notes: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return updateProjectChecklistStatus(input.id, input.status, input.notes); }),
    evidence: protectedProcedure.input(z.object({ projectId: z.number().int().positive() })).query(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return listProjectEvidence(input.projectId); }),
    uploadEvidence: protectedProcedure.input(z.object({ projectId: z.number().int().positive(), taskId: z.number().int().positive().optional(), title: z.string().min(2).max(255), filename: z.string().min(1).max(255), mimeType: z.string().min(1).max(120), base64: z.string().max(7_000_000) })).mutation(async ({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); const buffer = Buffer.from(input.base64, "base64"); if (!canUploadProjectEvidence({ title: input.title, sizeBytes: buffer.byteLength })) throw new TRPCError({ code: buffer.byteLength > MAX_PROJECT_EVIDENCE_BYTES ? "PAYLOAD_TOO_LARGE" : "BAD_REQUEST", message: buffer.byteLength > MAX_PROJECT_EVIDENCE_BYTES ? "Evidências técnicas devem ter no máximo 5 MB." : "Informe um título de evidência entre 2 e 255 caracteres e um arquivo não vazio." }); const safeFilename = input.filename.replace(/[^a-zA-Z0-9._-]/g, "_"); const stored = await storagePut(`execution/${ctx.user.id}/${input.projectId}/${Date.now()}-${safeFilename}`, buffer, input.mimeType); return createProjectEvidence({ projectId: input.projectId, taskId: input.taskId, title: input.title, fileName: safeFilename, mimeType: input.mimeType, fileKey: stored.key, fileUrl: stored.url, uploadedBy: ctx.user.id }); }),
  }),
  notifications: router({
    list: protectedProcedure.query(({ ctx }) => listNotifications(ctx.user.id)),
    markRead: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => markNotificationRead(input.id, ctx.user.id)),
    sendTestEmail: protectedProcedure.input(z.object({ subject: z.string().trim().min(1).max(120).default("Teste SMTP — Raizon CRM") })).mutation(async ({ ctx, input }) => {
      requireProfile(ctx, ["admin"]);
      const info = await sendTitanEmail({ subject: input.subject, text: "Teste controlado de integração SMTP Titan do Raizon Intelligence CRM." });
      return { sent: true, messageId: info.messageId };
    }),
  }),
  intelligence: router({
    radar: protectedProcedure.query(({ ctx }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return getIntelligenceRadar(); }),
    metrics: protectedProcedure.query(({ ctx }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return getCommercialMetrics(); }),
    followUps: protectedProcedure.mutation(({ ctx }) => { requireProfile(ctx, ["admin", "commercial"]); return runProposalFollowUps(); }),
    suggestions: protectedProcedure.input(z.object({ status: z.enum(["pending", "approved", "rejected"]).optional() }).optional()).query(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return listIntelligenceSuggestions(input?.status); }),
    generateSuggestion: protectedProcedure.input(z.object({ entityType: z.enum(["opportunity", "company", "proposal"]), entityId: z.number().int().positive().optional(), suggestionType: z.enum(["service", "summary", "missing_fields"]), sourceSnapshot: z.string().min(2).max(20_000) })).mutation(async ({ ctx, input }) => {
      requireProfile(ctx, ["admin", "commercial", "technical"]);
      const result = await invokeLLM({
        model: "gpt-5-mini",
        messages: [
          { role: "system", content: "Você é um assistente interno da Raizon Ambiental. Analise somente os dados fornecidos. Não declare irregularidade jurídica, não invente dados, não emita proposta e não crie obrigação. Retorne JSON objetivo com suggestion, rationale, missingFields e confidence. Toda saída é uma sugestão que exige aprovação humana." },
          { role: "user", content: `Tipo de sugestão: ${input.suggestionType}. Dados de origem: ${input.sourceSnapshot}` },
        ],
        response_format: { type: "json_schema", json_schema: { name: "raizon_intelligence_suggestion", strict: true, schema: { type: "object", properties: { suggestion: { type: "string" }, rationale: { type: "string" }, missingFields: { type: "array", items: { type: "string" } }, confidence: { type: "number", minimum: 0, maximum: 1 } }, required: ["suggestion", "rationale", "missingFields", "confidence"], additionalProperties: false } } },
      });
      const content = result.choices[0]?.message?.content;
      const suggestion = typeof content === "string" ? content : JSON.stringify(content || { suggestion: "", rationale: "", missingFields: [], confidence: 0 });
      let confidence = 0;
      try { confidence = Math.max(0, Math.min(1, Number(JSON.parse(suggestion).confidence || 0))); } catch { confidence = 0; }
      return createIntelligenceSuggestion({ entityType: input.entityType, entityId: input.entityId, suggestionType: input.suggestionType, sourceSnapshot: input.sourceSnapshot, suggestion, confidence: confidence.toFixed(2), status: "pending", createdBy: ctx.user.id });
    }),
    reviewSuggestion: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["approved", "rejected"]) })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return reviewIntelligenceSuggestion(input.id, input.status, ctx.user.id); }),
    recordValidation: protectedProcedure.input(z.object({ regulatoryActId: z.number().int().positive(), sourceVersion: z.string().trim().max(120).optional(), publishedStatus: z.string().trim().max(120).optional(), expiresAt: z.date().optional(), evidenceUrl: z.string().url().max(700), rawEssential: z.string().trim().min(2).max(20_000), confidence: z.number().min(0).max(1), validationStatus: z.enum(["unverified", "confirmed", "needs_review"]) })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return recordRegulatoryValidation({ ...normalizePersistedDates(input, ["expiresAt"]), validatedBy: ctx.user.id }); }),
  }),
  dashboard: router({
    stats: protectedProcedure.query(() => getDashboardStats()),
    activities: protectedProcedure.input(z.object({ companyId: z.number().int().positive().optional(), opportunityId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return listRecentActivities(input); }),
    recurring: protectedProcedure.query(() => listUpcomingRecurring()),
    cetesbLeadStatus: protectedProcedure.query(() => getCetesbLeadStatus()),
    commercialFunnel: protectedProcedure.query(() => getCommercialFunnelSummary()),
    operationalCoverage: protectedProcedure.query(() => getOperationalCoverage()),
    myQueue: protectedProcedure.query(({ ctx }) => listOperationalQueue(ctx.user.id)),
  }),
  leads: router({
    list: protectedProcedure.input(z.object({ commercialStatus: leadStageSchema.optional(), ownerId: z.number().int().positive().optional() }).optional()).query(({ input }) => listLeads(input)),
    create: protectedProcedure.input(z.object({ companyId: z.number().int().positive(), unitId: z.number().int().positive().optional(), regulatoryActId: z.number().int().positive().optional(), source: z.string().min(2), sourceRecordKey: z.string().max(180).optional(), candidateReason: z.string().optional(), regulatoryStatusSnapshot: z.string().optional(), technicalPriority: z.enum(["A", "B", "C", "D"]).default("C"), commercialPriority: z.enum(["A", "B", "C", "D"]).default("B"), nextAction: z.string().min(3), nextActionAt: z.date() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return createLead({ ...input, ownerId: ctx.user.id, regulatoryCollectedAt: input.regulatoryStatusSnapshot ? new Date() : undefined }); }),
    updateStatus: protectedProcedure.input(z.object({ id: z.number().int().positive(), commercialStatus: leadStageSchema, nextAction: z.string().min(3).optional(), nextActionAt: z.date().optional(), discardedReason: z.string().max(180).optional() })).mutation(async ({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial"]); const evidence = await getLeadTransitionEvidence(input.id); try { validateCommercialTransition(input.commercialStatus, input.nextAction, { ...evidence, lossReason: input.discardedReason }); } catch (error) { throw new TRPCError({ code: "BAD_REQUEST", message: error instanceof Error ? error.message : String(error) }); } return updateLeadCommercialStatus(input.id, input.commercialStatus, input.nextAction, input.nextActionAt, input.discardedReason); }),
    convertToClient: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial"]); return convertLeadToClient(input.id); }),
  }),
  companies: router({
    list: protectedProcedure.input(z.object({ search: z.string().optional(), relationshipStatus: z.enum(["prospect", "client", "inactive"]).optional() }).optional()).query(({ input }) => listCompanies(input?.search, input?.relationshipStatus)),
    create: protectedProcedure.input(z.object({ cnpj: cnpjSchema, legalName: z.string().min(2), tradeName: z.string().optional(), registrationStatus: z.string().max(80).optional(), companySize: z.string().max(80).optional(), mainCnae: z.string().max(20).optional(), address: z.string().max(255).optional(), addressNumber: z.string().max(30).optional(), addressComplement: z.string().max(120).optional(), neighborhood: z.string().max(120).optional(), postalCode: z.string().max(12).optional(), city: z.string().optional(), state: z.string().length(2).optional(), phone: z.string().max(30).optional(), email: z.string().email().max(255).optional().or(z.literal("")), website: z.string().max(255).optional(), segment: z.string().optional(), notes: z.string().optional(), relationshipStatus: z.enum(["prospect", "client", "inactive"]).default("client") })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return createCompany({ ...input, city: normalizeMunicipalityValue(input.city) || undefined, state: input.state?.toUpperCase(), email: input.email || undefined, source: "manual" }); }),
    bulkUpsert: protectedProcedure.input(z.object({ filename: z.string().optional(), source: z.string().default("import"), rows: z.array(z.object({ cnpj: z.string(), legalName: z.string(), tradeName: z.string().optional(), city: z.string().optional(), state: z.string().optional(), segment: z.string().optional(), source: z.string().optional() })).max(1000) })).mutation(async ({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); const runId = await createImportRun({ source: input.source, filename: input.filename, createdBy: ctx.user.id }); try { const result = await bulkUpsertCompanies(input.rows); await finishImportRun(runId, { ...result, status: result.rejected > 0 ? "review_required" : "completed" }); return { ...result, runId }; } catch (error) { const errorMessage = error instanceof Error ? error.message : String(error); await finishImportRun(runId, { received: input.rows.length, inserted: 0, updated: 0, rejected: input.rows.length, status: "failed", errorMessage }); await createImportFailureNotification(ctx.user.id, runId, errorMessage); throw error; } }),
  }),
  units: router({
    list: protectedProcedure.input(z.object({ companyId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return listUnits(input?.companyId); }),
    create: protectedProcedure.input(z.object({ companyId: z.number().int().positive(), name: z.string().min(2), address: z.string().optional(), city: z.string().optional(), state: z.string().length(2).optional(), operationType: z.string().optional(), responsibleName: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return createUnit({ ...input, city: normalizeMunicipalityValue(input.city) || undefined }); }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive(), name: z.string().min(2).optional(), address: z.string().optional(), city: z.string().optional(), state: z.string().length(2).optional(), operationType: z.string().optional(), responsibleName: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); const { id, ...changes } = input; return updateUnit(id, { ...changes, city: normalizeMunicipalityValue(changes.city) || undefined }); }),
    archive: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return archiveUnit(input.id); }),
  }),
  contacts: router({
    list: protectedProcedure.input(z.object({ companyId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return listContacts(input?.companyId); }),
    create: protectedProcedure.input(z.object({ companyId: z.number().int().positive(), unitId: z.number().int().positive().optional(), name: z.string().min(2), jobTitle: z.string().optional(), phone: z.string().optional(), email: z.string().email().optional(), decisionRole: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return createContact({ ...input, phone: normalizePhoneValue(input.phone) || undefined, email: normalizeEmailValue(input.email) }); }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive(), name: z.string().min(2).optional(), jobTitle: z.string().optional(), phone: z.string().optional(), email: z.string().email().optional(), decisionRole: z.string().optional(), validationStatus: z.enum(["unverified", "verified", "invalid"]).optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); const { id, ...changes } = input; return updateContact(id, { ...changes, phone: normalizePhoneValue(changes.phone) || undefined, email: normalizeEmailValue(changes.email) }); }),
    archive: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return archiveContact(input.id); }),
  }),
  cnpj: router({
    lookup: protectedProcedure.input(z.object({ cnpj: z.string() })).query(({ input }) => lookupCnpj(input.cnpj)),
  }),
  imports: router({
    capabilities: protectedProcedure.query(() => ({ cnpj: "provider-ready", cetesb: "controlled-public-source", spAguas: "controlled-public-source" })),
    history: protectedProcedure.query(({ ctx }) => { requireProfile(ctx, ["admin", "technical"]); return listImportRuns(); }),
    pendingConflicts: protectedProcedure.input(z.object({ importRunId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return listPendingImportConflicts(input?.importRunId); }),
    decideConflict: protectedProcedure.input(z.object({ id: z.number().int().positive(), decision: z.enum(["accept_incoming", "keep_current", "accept_partial", "review", "reject"]), rationale: z.string().max(500).optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return decideImportConflict(input.id, ctx.user.id, input.decision, input.rationale); }),
  }),
  regulatory: router({
    list: protectedProcedure.query(({ ctx }) => { requireProfile(ctx, ["admin", "technical", "commercial"]); return listRegulatoryActs(); }),
    create: protectedProcedure.input(z.object({ companyId: z.number().int().positive(), source: z.string().min(2), agency: z.string().optional(), actType: z.string().min(2), actNumber: z.string().optional(), processNumber: z.string().optional(), publishedStatus: z.string().optional(), expiresAt: z.date().optional(), evidenceUrl: z.string().url().optional(), notes: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return createRegulatoryAct({ ...normalizePersistedDates(input, ["expiresAt"]), needsValidation: 1, collectedAt: new Date() }); }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive(), actType: z.string().min(2).optional(), actNumber: z.string().optional(), processNumber: z.string().optional(), publishedStatus: z.string().optional(), expiresAt: z.date().optional(), evidenceUrl: z.string().url().optional(), notes: z.string().optional(), needsValidation: z.number().int().min(0).max(1).optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); const { id, ...changes } = input; return updateRegulatoryAct(id, normalizePersistedDates(changes, ["expiresAt"])); }),
    archive: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return archiveRegulatoryAct(input.id); }),
  }),
  evidence: router({
    list: protectedProcedure.input(z.object({ regulatoryActId: z.number().int().positive().optional(), companyId: z.number().int().positive().optional() })).query(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return listEvidenceFiles(input); }),
    archive: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return archiveEvidenceFile(input.id); }),
    upload: protectedProcedure.input(z.object({ filename: z.string().min(1).max(255), mimeType: z.string().min(1).max(120), base64: z.string().max(7_000_000), companyId: z.number().int().positive().optional(), unitId: z.number().int().positive().optional(), regulatoryActId: z.number().int().positive().optional(), opportunityId: z.number().int().positive().optional(), source: z.string().default("manual"), notes: z.string().optional() })).mutation(async ({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); const buffer = Buffer.from(input.base64, "base64"); if (buffer.byteLength > 5 * 1024 * 1024) throw new TRPCError({ code: "PAYLOAD_TOO_LARGE", message: "Evidências devem ter no máximo 5 MB." }); const stored = await storagePut(`evidence/${ctx.user.id}/${input.filename}`, buffer, input.mimeType); const { base64: _base64, ...metadata } = input; return createEvidenceFile({ ...metadata, sizeBytes: buffer.byteLength, storageKey: stored.key, storageUrl: stored.url, uploadedBy: ctx.user.id, collectedAt: new Date() }); }),
  }),
  opportunities: router({
    list: protectedProcedure.query(() => listOpportunities()),
    create: protectedProcedure.input(z.object({ companyId: z.number().int().positive(), title: z.string().min(2), serviceType: z.string().min(2), source: z.string().optional(), technicalPriority: z.enum(["A", "B", "C", "D"]).default("C"), commercialPriority: z.enum(["A", "B", "C", "D"]).default("B"), estimatedValue: z.string().optional(), criticalDate: z.date().optional(), nextAction: z.string().optional(), nextActionAt: z.date().optional(), deliverables: z.string().optional(), pendingItems: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial"]); return createOpportunity({ ...normalizePersistedDates(input, ["criticalDate", "nextActionAt"]), ownerId: ctx.user.id, probability: 20 }); }),
    updateStage: protectedProcedure.input(z.object({ id: z.number().int().positive(), stage: z.enum(["new", "enrichment", "actionable", "contacted", "qualified", "diagnosis", "scoping", "proposal", "negotiation", "approved", "won", "contracting", "execution", "delivery", "closed", "aftercare", "lost", "nurture", "discarded"]), lossReason: z.string().trim().min(2).optional() }).refine((input) => input.stage !== "lost" || Boolean(input.lossReason), { message: "Informe o motivo da perda." })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial"]); return updateOpportunityStageWithLossReason(input.id, input.stage, input.lossReason); }),
    updateDetails: protectedProcedure.input(z.object({ id: z.number().int().positive(), ownerId: z.number().int().positive().optional(), title: z.string().min(2).optional(), serviceType: z.string().min(2).optional(), estimatedValue: z.string().optional(), criticalDate: z.date().optional(), nextAction: z.string().optional(), nextActionAt: z.date().optional(), lossReason: z.string().optional(), notes: z.string().optional(), deliverables: z.string().optional(), pendingItems: z.string().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial"]); const { id, ...changes } = input; return updateOpportunityDetails(id, normalizePersistedDates(changes, ["criticalDate", "nextActionAt"])); }),
  }),
  activities: router({
    create: protectedProcedure.input(z.object({ companyId: z.number().int().positive(), opportunityId: z.number().int().positive().optional(), channel: z.string().min(2), objective: z.string().optional(), outcome: z.string().optional(), nextAction: z.string().optional(), nextActionAt: z.date().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "commercial", "technical"]); return createActivity({ ...normalizePersistedDates(input, ["nextActionAt"]), ownerId: ctx.user.id }); }),
  }),
  recurring: router({
    create: protectedProcedure.input(z.object({ companyId: z.number().int().positive(), title: z.string().min(2), recurrenceType: z.string().min(2), dueAt: z.date(), regulatoryActId: z.number().int().positive().optional() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return createRecurringItem({ ...normalizePersistedDates(input, ["dueAt"]), ownerId: ctx.user.id }); }),
    complete: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => { requireProfile(ctx, ["admin", "technical"]); return completeRecurringItem(input.id, ctx.user.id); }),
  }),
});

export type AppRouter = typeof appRouter;
